name: Build project and upload artifacts
on:
  push:
    branches: [ master, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew core:build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: core-build
          path: core/build/libs/*.jar
          retention-days: 7
